modLoader = "javafml"
loaderVersion = "[2,)"
license = "LICENSE"

[[mods]]
modId = "geostrata"
version = "${version}"
displayName = "GeoStrata"
authors = "Alkeari"
description = "Replaces overworld stone with 27 geological stone types."

[[mixins]]
config = "geostrata.common.mixins.json"

[[dependencies.geostrata]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.geostrata]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.geostrata]]
modId = "architectury"
type = "required"
versionRange = "[13,)"
ordering = "NONE"
side = "BOTH"
